# Sales columns as parameters
Sales_OrderID: "Sales.OrderID"
Sales_CustomerID: "Sales.CustomerID"
Sales_ProductID: "Sales.ProductID" 
Sales_Quantity: "Sales.Quantity"
Sales_SalesDate: "Sales.SalesDate"

# Customer columns as parameters
Customers_CustomerID: "Customers.CustomerID"
Customers_FirstName: "Customers.FirstName"
Customers_LastName: "Customers.LastName"
Customers_Email: "Customers.Email"

# Products columns as parameters
Products_ProductID: "Products.ProductID"
Products_ProductName: "Products.ProductName"
Products_Category: "Products.Category"
Products_Price: "Products.Price"
Products_SalesDate: "Products.SalesDate"

# Stock columns as parameters
Stock_ProductID: "Stock.ProductID"
Stock_QuantityAvailability: "Stock.QuantityAvailability"

