# Sales columns as parameters
Sales_SalesID: "Sales.SalesID"
Sales_OrderID: "Sales.OrderID"
Sales_CustomerID: "Sales.CustomerID"
Sales_ProductID: "Sales.ProductID" 
Sales_Quantity: "Sales.Quantity"
Sales_SalesDate: "Sales.SalesDate"
Sales_SalesValue: "Sales.SalesValue"

# Customer columns as parameters
Customers_CustomerID: "Customers.CustomerID"
Customers_FirstName: "Customers.FirstName"
Customers_LastName: "Customers.LastName"
Customers_Email: "Customers.Email"

# Column names for the inventory source system depicted as parameters
# It is a key-value structure and the key can be accessed within a pipeline
# using the prefix "params:"
# E.g. to include the Product Name as parameter, you need to include the 
# entry as input using variable_name = "params:Product_ProductName"

# Product columns as parameters

Products_ProductID: "Products.ProductID"
Products_ProductName: "Products.ProductName"
Products_Category: "Products.Category"
Products_Price: "Products.Price"
# Products_SalesDate: "Products.SalesDate"

# Stock columns as parameters
Stock_ProductID: "Stock.ProductID"
Stock_Quantity: "Stock.Quantity"


