# Sales columns as parameters
Sales_SalesID: "Sales.SalesID"
Sales_OrderID: "Sales.OrderID"
Sales_CustomerID: "Sales.CustomerID"
Sales_ProductID: "Sales.ProductID" 
Sales_Quantity: "Sales.Quantity"
Sales_SalesDate: "Sales.SalesDate"
Sales_SalesValue: "Sales.SalesValue"

# Customer columns as parameters
Customers_CustomerID: "Customers.CustomerID"
Customers_FirstName: "Customers.FirstName"
Customers_LastName: "Customers.LastName"
Customers_Email: "Customers.Email"

# Column names for the inventory source system depicted as parameters
# It is a key-value structure and the key can be accessed within a pipeline
# using the prefix "params:"
# E.g. to include the Product Name as parameter, you need to include the 
# entry as input using variable_name = "params:Product_ProductName"

# Product columns as parameters

Products_ProductID: "Products.ProductID"
Products_ProductName: "Products.ProductName"
Products_Category: "Products.Category"
Products_Price: "Products.Price"
# Products_SalesDate: "Products.SalesDate"

# Stock columns as parameters
Stock_ProductID: "Stock.ProductID"
Stock_Quantity: "Stock.Quantity"

# Top products 
n_top_products: 10


Projections:
  Sales_Customers:
    Customers_CustomerID : ""
    Sales_CustomerID : ""
  Sales_Products:
    Sales_CustomerID            : ""
    Products_ProductName        : ""
    Products_Category           : ""
    Products_Price         : ""
  Sales_Products_Stock:
    Sales_OrderID         : ""
    Products_ProductName  : ""
    Products_Category     : ""
    Products_Price        : ""
    Stock_ProductID       : ""
    Stock_Quantity    : ""

Inventory:
  Products:
    Products_ProductID : ""
    Products_ProductName    : ""            
    Products_Category            : ""       
    Products_Price  : ""
  Stock:
    Stock_ProductID : ""
    Stock_Quantity : ""

Sales:
  Sales_OrderID : ""                                   
  Sales_CustomerID  : ""                               
  Sales_ProductID  : ""                                
  Sales_Quantity  : ""                                 
  Sales_SalesDate  : ""                                
  Sales_SalesValue  : ""

Sales_Measures:        
  Products:
    Products_ProductID  : "" 
  Sales:
    Sales_SalesValue : ""
  Inventory:
    Products:
      Products:
        Products_ProductID : ""
  # Sales_SalesValue    : ""              
  Sales_OrderID       : ""                    
  # Sales_SalesValue    : ""      

Customer:
  Customers_CustomerID         : ""                 
  Customers_FirstName          : ""                 
  Customers_LastName          : ""                  
  Customers_Email  : ""


