[tool.kedro]
package_name = "data_lineage"
project_name = "data_lineage"
kedro_init_version = "0.18.9"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/data_lineage -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
